version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hemlig_passord_23
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

# For å sette opp MONGODB-miljøvariabelen, bruk følgende streng:
# MONGODB=mongodb://root:hemlig_passord_23@localhost:27017
